# Generated by Django 5.0.4 on 2024-05-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='star',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
