# Generated by Django 5.0.4 on 2024-05-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelscomment',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelscomment',
            name='persons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_comments', to='booking_app.person'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name', 'address'], name='booking_app_name_c86283_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['star'], name='star_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['address'], name='address_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name', 'first_name'], name='booking_app_last_na_23b279_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_name'], name='first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['age'], name='age_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sex'], name='sex_idx'),
        ),
    ]
