# Generated by Django 5.0.4 on 2024-05-09 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotels_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=200, null=True)),
                ('book_time', models.DateTimeField(auto_now_add=True)),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('star', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=40)),
                ('rating', models.FloatField(null=True)),
                ('persons', models.ManyToManyField(to='booking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='HotelsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotel')),
                ('persons', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card_number', models.IntegerField(null=True)),
                ('serial', models.CharField(max_length=30, null=True)),
                ('persons', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotels',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='hotels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotel'),
        ),
    ]
