# Generated by Django 5.0.4 on 2024-05-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_bookinfo_hotel_hotelscomment_profile_delete_hotels_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInfo',
            new_name='Book_order_info',
        ),
        migrations.CreateModel(
            name='Hotel_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('hotels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('persons', models.ManyToManyField(null=True, to='booking_app.person')),
                ('hotel_owner', models.ManyToManyField(null=True, to='booking_app.hotel_owner')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hotel_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.hotel_owner'),
        ),
    ]
