# Generated by Django 5.0.4 on 2024-06-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_remove_room_hotel_user_photo_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelscomment',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
