# Generated by Django 5.0.4 on 2024-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_hotelscomment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelscomment',
            name='photo',
            field=models.ImageField(null=True, upload_to='comment_photo/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='user_photo/', verbose_name='Photo'),
        ),
    ]
